### ISSUE TITLE
Kundera 2.2 class loading issue

### ISSUE THREAD

**Issue by schp** [Impetus/kundera#146]
I tried to use Kundera 2.2 under Glassfish 3.1 with MongoDB 2.2. I placed the Kundera jars (along with their dependencies) under the <glassfish>/glassfish/domains/domain1/lib directory, because I did not want to package them inside the application WAR file. Now the problem I have detected is that altough method findResourcesByContextLoader in class ClasspathReader used (correctly) the current thread's class loader to find entitiy classes, method scanClassAndPutMetadata in class MetamodelConfiguration used its own classloader, and therefore it did not find the entity classes in the web application. However, if you change the line

``` java
Class<?> clazz = Class.forName(className);
```

to

``` java
Class<?> clazz = Thread.currentThread().getContextClassLoader().loadClass(className);
```

it works correctly.

Thanks,
       Peter

**Comment by kkmishra** [comment]
Thanks Peter.
It is fixed as you suggested 

commit  a2e0153c31c4a85bfd67777e99e49548831905b6

please verify .

Cheers, 
Kuldeep

**Comment by schp** [comment]
Thanks for the fix. I am not very proficient in maven, so it is possible that I have misconfigured something, but with the current 2.3-SNAPSHOT I still get the same error. I suspect that the class loader associated with the PersistenceUnitMetadata class (variable puMetadata) is still the same class loader which loaded the JARs from the Glassfish domain/domain1/lib directory and therefore does not "see" the entity classes present in the web app.

Thanks,
Peter

**Comment by mevivs** [comment]
Planning to fix and test it on glassfish as an external kundera jar. Will be fixed in 2.3

-Vivek

**Comment by kkmishra** [comment]
Hi Peter,
I tried but couldn't replicate your issue. I am attaching image screenshots of /glassfish/domains/domain1/lib and /glassfish/domains/domain1/applications/twitample/WEB-INF/lib folders.   (twitample is name of my web application).

This worked for me, Please compare this with your configuration and resolve disrepency (if any)
 I will be happy to send you my entire code (which is also available at https://github.com/xamry/twitample)

![Screenshot-2](https://f.cloud.github.com/assets/1187910/78194/a8aeac2e-6174-11e2-9065-2dc9c8794141.png)
![Screenshot-3](https://f.cloud.github.com/assets/1187910/78223/1e7813fa-6175-11e2-814d-5c44e2873812.png)

Thanks 
Kuldeep

**Comment by schp** [comment]
Hi Kuldeep,

The screenshots represent the situation I was dealing with, so if your test project worked for you, the problem was indeed fixed. Unfortunately I could not test the fix with my own project because I did not manage to build Kundera from source. However, if you happen to have a fairly recent version in a publicly accessible maven repo, I will gladly test it myself.

Thanks,
Peter

**Comment by mevivs** [comment]
I guess, mvn clean install -DskipTests should work for you to build Kundera. 
2.3 release(releasing soon) will be available on public maven repo.

Cheers,

-Vivek

**Comment by mevivs** [comment]
Any update on this? Shall i mark it close for 2.3(releasing today) ?

**Comment by schp** [comment]
I can confirm that in version 2.3 the problem has been fixed, the issue can be closed.

Thanks,
Peter

**Comment by mevivs** [comment]
Closing..
