### ISSUE TITLE
Exception in thread "main" InvalidRequestException(why:Not enough bytes to read value of component 0)

### ISSUE THREAD

**Issue by apolishetty** [Impetus/kundera#174]
CREATE TABLE emp (
  empid text PRIMARY KEY,
  empanme text,
  empdept text
) WITH
  bloom_filter_fp_chance=0.010000 AND
  caching='KEYS_ONLY' AND
  comment='' AND
  dclocal_read_repair_chance=0.000000 AND
  gc_grace_seconds=864000 AND
  read_repair_chance=0.100000 AND
  replicate_on_write='true' AND
  compaction={'class': 'SizeTieredCompactionStrategy'} AND
  compression={'sstable_compression': 'SnappyCompressor'};

jars:
"libthrift-0.6.1.jar" "cassandra-all-1.0.9.jar" "cassandra-clientutil-1.0.9.jar" "cassandra-thrift-1.0.9.jar"  and alrad uised the log jars also
Column empid = new Column();
            empid.setName("empid".getBytes());
            empid.setValue("12".getBytes());
            empid.setTimestamp(System.currentTimeMillis());

```
        Column empanme = new Column();
        empanme.setName("empanme".getBytes());
        empanme.setValue("cass".getBytes());
        empanme.setTimestamp(System.currentTimeMillis());

        Column empdept = new Column();
        empdept.setName("empdept".getBytes());
        empdept.setValue("Tester".getBytes());
        empdept.setTimestamp(System.currentTimeMillis());

      client.insert(rowid, columnParent, empid, ConsistencyLevel.ONE);
      client.insert(rowid, columnParent, empanme, ConsistencyLevel.ONE);
      client.insert(rowid, columnParent, empdept, ConsistencyLevel.ONE);
```

when i was inserting the data into cassandra database using thrift api(simple java application) it showing  following exception:Exception in thread "main" InvalidRequestException(why:Not enough bytes to read value of component 0)

could you plz any one help me why tjhis erros is cmg...

**Comment by mevivs** [comment]
This is an issue with CQL and thrift interoperability of Cassandra. If you create your column family via Cassandra-cli, it should be fine. Try this:

```
create column family emp with key_validation_class='UTF8Type' and default_validation_class='UTF8Type' and comparator='UTF8Type'; 
```

**Comment by mevivs** [comment]
Shall we close on this?

-Vivek

**Comment by mevivs** [comment]
Such interoperability issues have been resolved and will be releasing with 2.5

Please verify.

**Comment by mevivs** [comment]
Released with 2.5. Please verify.

-Vivek

**Comment by MazizEsa** [comment]
Hi Vivek.
I've tried with kundera 2.8 and created the table / column family via CQL. The problem still persist. 
It is ok if I've created the table using cassandra-cli.
Please advise.

**Comment by MazizEsa** [comment]
I've found out that, if you've created with CQL and included "WITH COMPACT STORAGE" in the create table statement, you can insert data fine. My understanding it should work regardless of the "With Compact Storage" option?

**Comment by mevivs** [comment]
Please use one of them either CQL3 or thrift.  "WITH COMPACT STORAGE" is for thrift compatible column families.

-Vivek

**Comment by MazizEsa** [comment]
Sorry, when you mentioned use either CQL3 or thrift, what are you referring to? and where to change this setting?

**Comment by mevivs** [comment]
If you are creating column families via CQL3, please use CQL3 via Kundera for dml operations. Similarly if column families created via thrift, please use thrift for the same.

```
em = emf.createEntityManager();
        Map<String, Client> clients = (Map<String, Client>) em.getDelegate();
        Client client = clients.get(PERSISTENCE_UNIT);
        ((CassandraClientBase) client).setCqlVersion("3.0.0");
```

Have a look at:
https://github.com/impetus-opensource/Kundera/blob/trunk/src/kundera-cassandra/src/test/java/com/impetus/client/crud/compositeType/CassandraCompositeTypeTest.java

It is also possible to set it while creating entity manager factory

-Vivek

**Comment by MazizEsa** [comment]
Thanks Vivek. It's working after changing the mentioned setting.

Regards,
Maziz.
