### ISSUE TITLE
problems with kundera automatic schema generation on DB with tables with composite keys

### ISSUE THREAD

**Issue by emgsilva** [Impetus/kundera#239]
Hi,

I was testing the use of “automatic schema generation” that Kundera provides, so that I can integrate this in my Cassandra DB - that already is running, and for which I created the tables using cassandra-cli/cqlsh. However, and since I do use “composite keys”, I did three tests to learn how I could integrate the “auto schema generation”. The first two tests use Kundera 2.2, the version I still use on my project, and in the third I used the latest stable version of Kundera (2.4): 

**Test 1:**
- three tables: table1 -(1-m)->table2-(1-m)->table3
- all of the tables have “non-composite” keys, so a single key
- table3 has a “secondary” index
- kundera configuration with: `<property name="kundera.ddl.auto.prepare" value="create”/>`
- Results: everything works fine (the creation of schemas, storing of data, get data from all the tables - including by secondary index). I also could get access to them via cassandra-cli and "cqlsh —cql3". When using the kundera configuration with “create” it takes almost 10 seconds (every time!) to setup the entity manager (I suppose because of the drop tables, create new, etc…)… when I change to “update” it is very fast.

**Test 2:**
- changed table1 to have a “composite key” composed of two elements (two strings)… kept all the rest
- I do have the “CQL3” client configured: `((CassandraClientBase) client).setCqlVersion(CassandraConstants.CQL_VERSION_3_0);` … but I get exactly the same results if I comment it
- Results: the tables get created (I can see them using cassandra-cli)… however, in my test application Kundera gives me this error in the “persist” command:

```
ERROR [main] (ThriftClient.java:163) - Error while persisting record. Details: null
Exception in thread "main" com.impetus.kundera.KunderaException: com.impetus.kundera.KunderaException: InvalidRequestException(why:line 1:172 no viable alternative at character ']')
     at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:208)
     at com.sigmabees.tests.KunderaAutoGenerationTest1.main(KunderaAutoGenerationTest1.java:64)
Caused by: com.impetus.kundera.KunderaException: InvalidRequestException(why:line 1:172 no viable alternative at character ']')
     at com.impetus.client.cassandra.thrift.ThriftClient.onPersist(ThriftClient.java:164)
     at com.impetus.kundera.client.ClientBase.persist(ClientBase.java:83)
     at com.impetus.client.cassandra.thrift.ThriftClient.persist(ThriftClient.java:126)
     at com.impetus.kundera.lifecycle.states.ManagedState.handleFlush(ManagedState.java:193)
     at com.impetus.kundera.graph.Node.flush(Node.java:525)
     at com.impetus.kundera.persistence.PersistenceDelegator.flush(PersistenceDelegator.java:411)
     at com.impetus.kundera.persistence.PersistenceDelegator.persist(PersistenceDelegator.java:169)
     at com.impetus.kundera.persistence.EntityManagerImpl.persist(EntityManagerImpl.java:202)
     ... 1 more
Caused by: InvalidRequestException(why:line 1:172 no viable alternative at character ']')
     at org.apache.cassandra.thrift.Cassandra$execute_cql_query_result.read(Cassandra.java:33477)
     at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
     at org.apache.cassandra.thrift.Cassandra$Client.recv_execute_cql_query(Cassandra.java:1402)
     at org.apache.cassandra.thrift.Cassandra$Client.execute_cql_query(Cassandra.java:1388)
     at com.impetus.client.cassandra.CassandraClientBase.onpersistOverCompositeKey(CassandraClientBase.java:871)
     at com.impetus.client.cassandra.thrift.ThriftClient.onPersist(ThriftClient.java:151)
     ... 8 more
```

**Test 3:**
- using “composite keys” (like in Test 2) and Kundera 2.4
- get this error:

```
ERROR [main] (CassandraSchemaManager.java:899) - Error while creating schema in cassandra, Caused by:
org.apache.thrift.TApplicationException: Invalid method name: 'execute_cql3_query'
     at org.apache.thrift.TApplicationException.read(TApplicationException.java:108)
     at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:71)
     at org.apache.cassandra.thrift.Cassandra$Client.recv_execute_cql3_query(Cassandra.java:1562)
     at org.apache.cassandra.thrift.Cassandra$Client.execute_cql3_query(Cassandra.java:1547)
     at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.onCompoundKey(CassandraSchemaManager.java:514)
     at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.createKeyspaceAndTables(CassandraSchemaManager.java:882)
     at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.create(CassandraSchemaManager.java:243)
     at com.impetus.kundera.configure.schema.api.AbstractSchemaManager.handleOperations(AbstractSchemaManager.java:278)
     at com.impetus.kundera.configure.schema.api.AbstractSchemaManager.exportSchema(AbstractSchemaManager.java:118)
     at com.impetus.client.cassandra.schemamanager.CassandraSchemaManager.exportSchema(CassandraSchemaManager.java:141)
     at com.impetus.kundera.configure.SchemaConfiguration.configure(SchemaConfiguration.java:165)
     at com.impetus.kundera.configure.Configurator.configure(Configurator.java:65)
     at com.impetus.kundera.KunderaPersistence.initializeKundera(KunderaPersistence.java:104)
     at com.impetus.kundera.KunderaPersistence.createEntityManagerFactory(KunderaPersistence.java:77)
     at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:63)
     at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:47)
```

**Some questions/remarks:**

1) the `<property name="kundera.ddl.auto.prepare" value="update”/>` is extremely “expensive”, and if you do it every time you make a new kundera “entity manager” that will be very slow… (I tested it and takes around 10 seconds each time in my current setup… because this will drop and recreate the schema every time). Furthermore, it will “drop” the tables, i.e., will recreate them and throw the data aways! When I change to “update”, it goes very fast… and it is supposed to create new schemas if they do not exist. Would using “update” work for any situation or we need “create” for some situations?

2) when using the automatic schema generation, the “column names” are named in “Hexadecimal” (when you check them in cassandra-cl/cqlsh)… this is OK for the application (using kundera) but not so nice if you want to do some queries in the console, or if you want to use another client (not sure how this would work). 

3) I noticed (in Test 1) that we need to create the keyspace manually (for example in cassandra-cli)… isn’t this managed by Kundera auto schema creation too, like the tables creation?

4) how can we support kundera automatic schema creation if we have “composite keys”? Is this possible, or we can only have such a “automatic schema management” on tables that have no composite keys?

5) when I use version 2.4 in tests I have working correctly on version 2.2, I get another error, although with a common part, the “execute_cql3_query” method… which again leads me to think that there is still some issues with “composite keys” and CQL3… but in this case it is very strange, because with Kundera 2.2 it works perfectly… this is the error I get in the code that runs correctly in version 2.2:

```
ERROR [main] (CassandraClientBase.java:767) - Error while executing native CQL query Caused by:
org.apache.thrift.TApplicationException: Invalid method name: 'execute_cql3_query'
     at org.apache.thrift.TApplicationException.read(TApplicationException.java:108)
     at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:71)
     at org.apache.cassandra.thrift.Cassandra$Client.recv_execute_cql3_query(Cassandra.java:1562)
     at org.apache.cassandra.thrift.Cassandra$Client.execute_cql3_query(Cassandra.java:1547)
     at com.impetus.client.cassandra.CassandraClientBase.executeQuery(CassandraClientBase.java:699)
     at com.impetus.client.cassandra.thrift.ThriftClient.executeQuery(ThriftClient.java:823)
     at com.impetus.client.cassandra.CassandraClientBase.find(CassandraClientBase.java:598)
     at com.impetus.client.cassandra.CassandraClientBase.find(CassandraClientBase.java:545)
     at com.impetus.client.cassandra.thrift.ThriftClient.find(ThriftClient.java:311)
     at com.impetus.kundera.persistence.AbstractEntityReader.findById(AbstractEntityReader.java:70)
     at com.impetus.client.cassandra.query.CassandraEntityReader.findById(CassandraEntityReader.java:88)
     at com.impetus.kundera.lifecycle.states.ManagedState.handleFind(ManagedState.java:124)
     at com.impetus.kundera.graph.Node.find(Node.java:499)
     at com.impetus.kundera.persistence.PersistenceDelegator.find(PersistenceDelegator.java:270)
     at com.impetus.kundera.persistence.PersistenceDelegator.findById(PersistenceDelegator.java:213)
     at com.impetus.kundera.persistence.EntityManagerImpl.find(EntityManagerImpl.java:257)
```

Sorry for the long post… but I want to get these details clear in so that I decide to integrate this on the extensions I will be making in my application.

Cheers!

**Comment by pires** [comment]
Which version of Cassandra are you using? It seems that you're using a version prior than 1.2.0 (with thrift IDL < 19.35).

Also, yes, auto DDL generation does take care of schema creation. At least, that's the case for me, but I don't use composite keys, yet.

**Comment by emgsilva** [comment]
I use cassandra version 1.1.6 in my project (did not update yet to the latest version)... that could be something, although I am not sure.

As mentioned I do get schema creation (although I have still questions around the "create" and "update"), but the problem is with the case where I use "composite keys"... I get all the errors mentioned in the issue.

**Comment by pires** [comment]
Regarding DDL generation, _automagical_ creation/update is great. Yet, I wouldn't recommend using it for production systems, where you should migrate your schema(s) manually. Once again, I find this DDL generation mechanism really useful for testing purposes.

**Comment by pires** [comment]
@emgsilva have you followed https://github.com/impetus-opensource/Kundera/wiki/Using-Compound-keys-with-Kundera? If so, then your problem with Kundera 2.4.0 should be Cassandra version.

**Comment by emgsilva** [comment]
@pires thank you, but maybe I was not clear in my questions... I do know how to implement composite keys (and know that they need CQL3), actually they are already implemented in my Cassandra DB at the moment (I have defined them manually using cassandra-cli and cqlsh --cql3 some months ago)... However, I would like to know if I could generate/update them (composite keys) from the Entity Classes annotations (using the DDL generation of Kundera)... that is my main issue, which I still do not understand... well I do have some other questions/remarks, which I listed in the original post, and would like to see what is the current status of Kundera on those points. Cheers!

**Comment by pires** [comment]
From my understanding, the annotations described in the link in my last comment are enough for composite key DDL generation. @mevivs seems to be the man to give a more concrete answer, though.

**Comment by emgsilva** [comment]
Yes, those are the annotations used to support Composite Keys... On my tests I do get the tables with no composite keys generated... but the tables with composite key do not get generated... I use the same annotations for a manually generated schema (using cqlsh --cql3) with composite keys (created in my project), and it gets correctly "persisted"... so there must be something else here.

**Comment by rsshilli** [comment]
Pires, I've read your link, but I'm still confused.  I'm on cassandra 1.2.3 and I'm seeing funkiness in the generated DDL, although unlike emgsilva, it is working.

My entity I'm persisting looks like this:

``` @Entity
@Table(name = "contacttouser", schema = "peoplelinker@cassandra_people_linker")
public class ContactToUser {
    @EmbeddedId
    private ContactToUserKey id;

    public ContactToUser() {
    }

    public ContactToUserKey getId() {
        return id;
    }

    public void setId(ContactToUserKey id) {
        this.id = id;
    }
}
```

My key looks like:

``` @Embeddable
public class ContactToUserKey implements Serializable {

    @Column
    private String contactId;

    @Column
    private String userId;

    public ContactToUserKey() {
    }
... getters & setters
```

Here's what cqlsh -3 reports got created:

```
cqlsh:peoplelinker> desc table contacttouser;

CREATE TABLE contacttouser (
  key blob,
  column1 text,
  value blob,
  PRIMARY KEY (key, column1)
) WITH COMPACT STORAGE AND
  bloom_filter_fp_chance=0.010000 AND
  caching='KEYS_ONLY' AND
  comment='' AND
  dclocal_read_repair_chance=0.000000 AND
  gc_grace_seconds=864000 AND
  read_repair_chance=0.100000 AND
  replicate_on_write='true' AND
  populate_io_cache_on_flush='false' AND
  compaction={'class': 'SizeTieredCompactionStrategy'} AND
  compression={'sstable_compression': 'SnappyCompressor'};
```

Where did key, column1 and value come from?  And why are key & value blobs?  I'm using a String.  When I try to do:

```
                ContactToUserKey contactToUserKey = new ContactToUserKey(contact.getId(), user.getId());
                ContactToUser contactToUser = entityManager.find(ContactToUser.class, contactToUserKey);
```

Kundera complains because, rightfully so, the table makes no sense:

```
InvalidRequestException(why:Undefined name contactId in where clause ('contactId EQ 'A5Sp4hfW3j''))
        at org.apache.cassandra.thrift.Cassandra$execute_cql3_query_result.read(Cassandra.java:37849)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:78)
        at org.apache.cassandra.thrift.Cassandra$Client.recv_execute_cql3_query(Cassandra.java:1562)
        at org.apache.cassandra.thrift.Cassandra$Client.execute_cql3_query(Cassandra.java:1547)
        at com.impetus.client.cassandra.CassandraClientBase.executeCQLQuery(CassandraClientBase.java:1661)
        at com.impetus.client.cassandra.CassandraClientBase$CQLClient.executeQuery(CassandraClientBase.java:1794)
        at com.impetus.client.cassandra.CassandraClientBase.executeQuery(CassandraClientBase.java:701)
        at com.impetus.client.cassandra.pelops.PelopsClient.executeQuery(PelopsClient.java:615)
        at com.impetus.client.cassandra.CassandraClientBase$CQLClient.find(CassandraClientBase.java:1875)
        at com.impetus.client.cassandra.CassandraClientBase.find(CassandraClientBase.java:608)
        at com.impetus.client.cassandra.CassandraClientBase.find(CassandraClientBase.java:560)
        at com.impetus.client.cassandra.pelops.PelopsClient.find(PelopsClient.java:140)
        at com.impetus.kundera.persistence.AbstractEntityReader.findById(AbstractEntityReader.java:72)
        at com.impetus.client.cassandra.query.CassandraEntityReader.findById(CassandraEntityReader.java:88)
        at com.impetus.kundera.lifecycle.states.ManagedState.handleFind(ManagedState.java:124)
        at com.impetus.kundera.graph.Node.find(Node.java:499)
        at com.impetus.kundera.persistence.PersistenceDelegator.find(PersistenceDelegator.java:267)
        at com.impetus.kundera.persistence.PersistenceDelegator.findById(PersistenceDelegator.java:210)
        at com.impetus.kundera.persistence.EntityManagerImpl.find(EntityManagerImpl.java:257)
        at com.onlyinsight.peoplelinker.server.oAuth.OAuthServlet.doGet(OAuthServlet.java:123)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
```

What am I doing wrong?

**Comment by mevivs** [comment]
ContactToUserKey should be annotated with @Embeddable annotation. is it there?

I would suggest you to try with latest 2.5 release and Cassandra 1.2.0 release.

-Vivek

**Comment by emgsilva** [comment]
Probably some of the issues I present in the original post are related with the fact that I am still using an old version of cassandra... and with a new 1.2.x version of Cassandra they will probably go away (I will give it a try soon), but would still be interesting to have some remarks from Kundera team on the issues raised, since some of them seem to be very pertinent for the Kundera users.

Concerning the issue presented by @rsshilli , and the auto-ddl option of Kundera for "composite key" tables, I can see no reason for the generation of "blob" data types (in my tests, with non composite key tables) the data types were correctly generated. Concerning the generation of "column names" (key, column1, value), maybe it would help if column declarations in the entity class are annotated with `@Column(name = "<columnname>")`:

```
@Embeddable
public class ContactToUserKey implements Serializable {

    @Column(name = "contactid")
    private String contactId;

    @Column(name = "userid")
    private String userId;

    ...
```

meaning that Kundera would (?) "force" those "weird" column names to be as the ones declared in the persistency entity class... Is this possible @mevivs , and again do you have some tests on your side that auto-ddl works as expected with composite key tables? 

Cheers!

**Comment by mevivs** [comment]
Test cases on auto schema generation are:
1.https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-cassandra/src/test/java/com/impetus/client/crud/compositeType/CompositeDataTypeTest.java

{ This one automatically creates schema with all supported data type for composite columns}. Please refer src/test/resources/META-INF/persistence.xml for "compositedatatype" persistence unit.
1. https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-cassandra/src/test/java/com/impetus/client/crud/compositeType/CassandraCompositeTypeTest.java

{ This one automatically creates schema for simple composite columns}. Please refer src/test/resources/META-INF/persistence.xml for "composite_pu" persistence unit.
1. https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-cassandra/src/test/java/com/impetus/client/crud/compositeType/CQLTranslatorTest.java

{ Recent 2.5 release now solves interoperability issues b/w CQL and thrift. This one covers that part }

-Vivek

**Comment by mevivs** [comment]
For columns like, "key" and "column1". It is created by CQL. "Key" is default name representation via cqlsh for row key. Any column without a name automatically given a name like "column1" in cassandra. We have seen such issues in releases before 2.5 but not with "composite keys" !

@emgsilva , @rsshilli : In case you still getting such issues with schema creation, kindly share your code snippets with us(may be in form of simple projects). We will verify those with corresponding releases(2.4,2.3 etc) and will confirm whether those are fixes with 2.5 or not.

Hope it helps.

Cheers,
-Vivek

**Comment by rsshilli** [comment]
Hey guys - thanks for the responses.  Sorry, my original comment was a little vague:
- ContactToUserKey is annotated with @Embeddable tag - I forgot to copy that in.  
- Eduardo, I tried adding the @Column(name="...")  tags but that didn't help - same issue
- I forgot to mention that I am running on the new Kundera 2.5 - not 2.4 or earlier

I'm at a loss what I'm doing wrong.  I still haven't looked over your test cases but I'll do that in a bit to see if something pops out at me that I'm doing wrong.

**Comment by rsshilli** [comment]
I found the bug.  It's in com.impetus.client.cassandra.schemamanager.CassandraSchemaManager#updateTables.  If I set the auto ddl strategy to "create", everything works fine.  I had it on "update" and that was why it was screwing up.  You need to replace line 813 with something like this (copied from addTablesToKeyspace):

```
-                    cassandra_client.system_add_column_family(cfDef);
+            if (tableInfo.getTableIdType() != null && tableInfo.getTableIdType().isAnnotationPresent(Embeddable.class))
+            {
+                if (tableInfo.getType() != null && tableInfo.getType().equals(Type.SUPER_COLUMN_FAMILY.name()))
+                {
+                    throw new SchemaGenerationException(
+                            "Composite/Compound columns are yet supported over Super column family by Cassandra",
+                            "cassandra", databaseName);
+                }
+                else
+                {
+                    onCompoundKey(tableInfo);
+                }
+            }
+            else
+            {
+                cassandra_client.system_add_column_family(getTableMetadata(tableInfo));
+                // Create Index Table if required
+                createInvertedIndexTable(tableInfo);
+            }
```

**Comment by mevivs** [comment]
Thanks. I will get it fixed for update functionality. Will post an update as soon as it's fixed.

-Vivek

**Comment by pires** [comment]
Is this fixed in trunk? Would be nice if commit logs were to reference the issues they're related to. I've found some closed issues without info on the fix code. This prevents people from learning about your base code from your changes :-(

You may be aware of it, but check _Commits + Issues_ at https://github.com/blog/831-issues-2-0-the-next-generation.

**Comment by mevivs** [comment]
Not yet fixed. Target for 2.6 release.  Yes, there have been such instances, we are trying to improve in it. Thanks for sharing links. It's really helpful!

Cheers,
-Vivek

**Comment by pires** [comment]
@rsshilli did you test the change you propose? Perhaps you could provide a fix and pull-request it.

**Comment by rsshilli** [comment]
@pires Sorry , I didn't test the fix.  I worked around it instead.

**Comment by mevivs** [comment]
Fixed and releasing with 2.6. Please verify.
-Vivek

**Comment by pires** [comment]
Works for me. Thanks.
