### ISSUE TITLE
attribute of the given name and type is not present in the managed type, for name:null

### ISSUE THREAD

**Issue by trungtv** [Impetus/kundera#497]
Hi all,
I am experienced following error for a specific jpa query: 

Exception in thread "main" com.impetus.kundera.query.QueryHandlerException: java.lang.IllegalArgumentException: attribute of the given name and type is not present in the managed type, for name:null
    at com.impetus.client.mongodb.query.MongoDBQuery.populateEntities(MongoDBQuery.java:143)
    at com.impetus.kundera.query.QueryImpl.getResultList(QueryImpl.java:153)
    at com.impetus.kundera.query.KunderaTypedQuery.getResultList(KunderaTypedQuery.java:250)
    at doraemon.modules.stampit.UserEngine.main(UserEngine.java:42)
Caused by: java.lang.IllegalArgumentException: attribute of the given name and type is not present in the managed type, for name:null
    at com.impetus.kundera.metadata.model.type.AbstractManagedType.checkForValid(AbstractManagedType.java:1010)
    at com.impetus.kundera.metadata.model.type.AbstractManagedType.getAttribute(AbstractManagedType.java:507)

My Entities: 

@Embeddable
public class UserInfo {

  @Column
  private String screenName;

  @Column
  private String fullName;
}

@Entity
@Table(name = "User", schema = "Test@Test_pu")
public class User {

  @Id
  @Column
  private String id;

  @Embedded
  private UserInfo userInfo;
}

Here is my query: 

TypedQuery<User> query =
        EM.createQuery("SELECT u FROM User u WHERE u.userInfo.fullName = abc", User.class);

Could you please explain what is wrong with my query? Do you have any solution for this task?

Thank you very much

**Comment by mevivs** [comment]
Looking into this.

-Vviek

**Comment by mevivs** [comment]
Issue has been fixed on current trunk and releasing with 2.9.1. 
Please verify.

-Vivek

**Comment by trungtv** [comment]
Thanks very much for your support.

**Comment by pavanraotk** [comment]
Hi, 

Not sure if I can open the thread or not, I am still getting the same error.

@NamedQueries({
        @NamedQuery(name = "ActivePoint.findAll", query = "SELECT activePoint FROM ActivePoint activePoint"),
        @NamedQuery(name = "ActivePoint.findByUserInternalId", query = "SELECT activePoint FROM ActivePoint activePoint WHERE activePoint.id.user_internal_id = :user_internal_id"),
        @NamedQuery(name = "ActivePoint.findByUserInternalIdAndType", query = "SELECT activePoint FROM ActivePoint activePoint WHERE activePoint.id.user_internal_id = :user_internal_id AND activePoint.type = :type"),
        @NamedQuery(name = "ActivePoint.findByUserInternalIdAndTs", query = "SELECT activePoint FROM ActivePoint activePoint WHERE activePoint.id.user_internal_id = :user_internal_id AND activePoint.ts = :ts")
})
public class ActivePoint {

```
@Id
@Embedded
ActivePointPK id;
```

....
}

@Embeddable
public class ActivePointPK {

```
@Column
UUID user_internal_id;

@Column
String type;

@Column
Timestamp ts;
```

....
}

DAO class function:

public ActivePoint getActivePointByUserInternalIdAndType(UUID user_internal_id, String type) throws Exception {
        ActivePoint activePoint = null;
        em = getEntityManager();
        TypedQuery<ActivePoint> getActivePointByUserInternalIdAndTypeQuery = em
                .createNamedQuery("ActivePoint.findByUserInternalIdAndType", ActivePoint.class);
        getActivePointByUserInternalIdAndTypeQuery.setParameter("user_internal_id", user_internal_id);
        getActivePointByUserInternalIdAndTypeQuery.setParameter("type", type);
        activePoint = getActivePointByUserInternalIdAndTypeQuery.getSingleResult();
        return activePoint;
    }

java.lang.IllegalArgumentException: attribute of the given name and type is not present in the managed type, for name:type

My Kundera versions:
<dependency>
            <groupId>com.impetus.kundera.core</groupId>
            <artifactId>kundera-core</artifactId>
            <version>3.1</version>
        </dependency>
        <dependency>
            <groupId>com.impetus.kundera.client</groupId>
            <artifactId>kundera-cassandra</artifactId>
            <version>3.1</version>
        </dependency>

**Comment by chhavigangwal** [comment]
Can you please update the id to :  

public class ActivePoint {

```
@EmbeddedId
ActivePointPK id;
```

and check at your end ?

Chhavi

**Comment by pavanraotk** [comment]
Hi Chhavi,

I tried @EmbeddedId, it still results in the same issue.

@Entity
@Table(name = "active_points")
@NamedQueries({ @NamedQuery(name = "ActivePoint.findAll", query = "SELECT
activePoint FROM ActivePoint activePoint"),
@NamedQuery(name = "ActivePoint.findByUserInternalId", query = "SELECT
activePoint FROM ActivePoint activePoint WHERE
activePoint.id.user_internal_id = :user_internal_id"),
@NamedQuery(name = "ActivePoint.findByUserInternalIdAndType", query =
"SELECT activePoint FROM ActivePoint activePoint WHERE
activePoint.id.user_internal_id = :user_internal_id AND activePoint.type =
:type"),
@NamedQuery(name = "ActivePoint.findByUserInternalIdAndTs", query = "SELECT
activePoint FROM ActivePoint activePoint WHERE
activePoint.id.user_internal_id = :user_internal_id AND activePoint.ts =
:ts") })
public class ActivePoint {

@EmbeddedId
ActivePointPK id;

@Column
Timestamp expiry;
...
}

On Wed, Nov 4, 2015 at 3:24 PM, chhavigangwal notifications@github.com
wrote:

> Can you please update the id to :
> 
> public class ActivePoint {
> 
> @EmbeddedId
> ActivePointPK id;
> 
> and check at your end ?
> 
> Chhavi
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/impetus-opensource/Kundera/issues/497#issuecomment-153592738
> .

## 

Regards

Pavan Rao T K
9844460190

**Comment by chhavigangwal** [comment]
@pavanraotk 

Your named queries are equivalent jpa queries and not the native one as you have use. Please see the example entity below to see the difference between NamedQuery and NamedNativeQuery and create an appropriate query for your usecase :

https://github.com/impetus-opensource/Kundera/blob/4bc732ebeea971d0449e4bf67a70023e83a72a8b/src/jpa-engine/core/src/test/java/com/impetus/kundera/metadata/processor/EntitySample.java

Chhavi

**Comment by pavanraotk** [comment]
Hi Chhavi,

It was a bad error from me.

@NamedQuery(name = "ActivePoint.findByUserInternalIdAndType", query =
"SELECT activePoint FROM ActivePoint activePoint WHERE
activePoint.id.user_internal_id = :user_internal_id AND activePoint._id_.type
= :type")

I was missing the *id. *Let me blame it on typo error and not my stupidity
:P.

Thanks for the information on native queries, I will use them in a
different case.

Thanks for investigating and helping me once again.

On Wed, Nov 4, 2015 at 3:58 PM, chhavigangwal notifications@github.com
wrote:

> @pavanraotk https://github.com/pavanraotk
> 
> Your named queries are equivalent jpa queries and not the native one as
> you have use. Please see the example entity below to see the difference
> between NamedQuery and NamedNativeQuery and create an appropriate query for
> your usecase :
> 
> https://github.com/impetus-opensource/Kundera/blob/4bc732ebeea971d0449e4bf67a70023e83a72a8b/src/jpa-engine/core/src/test/java/com/impetus/kundera/metadata/processor/EntitySample.java
> 
> Chhavi
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/impetus-opensource/Kundera/issues/497#issuecomment-153606573
> .

## 

Regards

Pavan Rao T K
9844460190
