### ISSUE TITLE
Problems continuing execution after an exception

### ISSUE THREAD

**Issue by everettj** [Impetus/kundera#68]
Using Kundera 2.0.6 with Cassandra, we are having a problem continuing application execution after an exception has occurred. Basically if we try to execute an operation (like persist) and that throws an exception, then any later operations will fail. 

If no exceptions are encountered, everything seems to work fine. We did not have this problem using 2.0.5.

Our persistence.xml:

``` xml
<persistence xmlns="http://java.sun.com/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/persistence
    http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
    version="2.0">
    <persistence-unit name="cassandra_pu">
        <provider>com.impetus.kundera.KunderaPersistence</provider>
        <properties>
            <property name="kundera.nodes" value="localhost"/>
            <property name="kundera.port" value="9160"/>
            <property name="kundera.keyspace" value="Kundera206Poc"/>
            <property name="kundera.dialect" value="cassandra"/>
            <property name="kundera.client.lookup.class" value="com.impetus.client.cassandra.pelops.PelopsClientFactory" />
            <property name="kundera.cache.provider.class" value="com.impetus.kundera.cache.ehcache.EhCacheProvider"/>
            <property name="kundera.cache.config.resource" value="/ehcache-test.xml"/>
        </properties>
    </persistence-unit>
</persistence>
```

The users column family:

```
create column family users
with comparator=UTF8Type
and default_validation_class=UTF8Type
and key_validation_class=UTF8Type
and column_metadata =
[
    {column_name: first_name, validation_class: UTF8Type, index_type: KEYS}
];
```

The User entity:

``` java
@Entity
@Table(name = "users", schema = "Kundera206Poc@cassandra_pu")
public class User {

    @Column(name = "age")
    private Integer age;

    @Column(name = "first_name")
    private String firstName;

    @Column(name = "last_name")
    private String lastName;

    @Id
    private String userId;

    // getters/setters
}
```

Our DAO, is pretty much a pass-through. We do use a container level EntityManager, which is different than your samples.

``` java
public class UserDao {

    @PersistenceContext(type = PersistenceContextType.EXTENDED)
    protected EntityManager em;

    public void delete(User user) {
        em.remove(user);
    }

    public void save(User user) {
        em.persist(user);
    }

    // other methods
}
```

We can recreate the issue with this test:

``` java
public class UserTest {

    private User user;

    @Autowired
    private UserDao userDao;

    @Before
    public void setUp() {
        user = new User();
        user.setUserId(UUID.randomUUID().toString());
        user.setFirstName("John");
        user.setLastName("Smith");
        user.setAge(20);

        // this save works fine because all columns are non-null
        userDao.save(user);
    }

    // This test passes, a KunderaException is thrown because the age column is null.
    @Test(expected = KunderaException.class)
    public void userCannotHaveNullColumn() {
        User newUser = new User();
        newUser.setUserId(UUID.randomUUID().toString());
        newUser.setFirstName("John");
        newUser.setLastName("Smith");
        // Age is null
        userDao.save(newUser);
    }

    @After
    public void tearDown() {
        // tear down will fail here with an exception
        userDao.delete(user);
        user = null;
    }
}
```

Running the above results in this stack trace (starting at the invocation of tearDown):

```

com.impetus.kundera.KunderaException: org.scale7.cassandra.pelops.exceptions.ModelException: Column value is null
    at com.impetus.client.cassandra.pelops.PelopsClient.persist(PelopsClient.java:390)
    at com.impetus.kundera.lifecycle.states.ManagedState.handleFlush(ManagedState.java:153)
    at com.impetus.kundera.graph.Node.flush(Node.java:478)
    at com.impetus.kundera.persistence.PersistenceDelegator.flush(PersistenceDelegator.java:290)
    at com.impetus.kundera.persistence.PersistenceDelegator.remove(PersistenceDelegator.java:248)
    at com.impetus.kundera.persistence.EntityManagerImpl.remove(EntityManagerImpl.java:153)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:365)
    at $Proxy20.remove(Unknown Source)
    at net.planettelex.kundera206poc.dao.ADao.delete(ADao.java:27)
    at net.planettelex.kundera206poc.entity.UserTest.tearDown(UserTest.java:44)
(many more lines)
```

When I trace this through, it appears that when PelopsClient.persist(Node node) is called it creates the wrong entity from the node data. I confirmed that our DAO is passing the right entity into persist().

Any ideas what might be causing this?

**Comment by mevivs** [comment]
Looking into this.

**Comment by mevivs** [comment]
Is this happening only in case of  " // Age is null" ?
I guess we might need to validate for null values, as i believe Pelops should taken care of this.

**Comment by everettj** [comment]
We recreate the problem by setting age to null, which causes an exception when user is persisted. The same will occur if we set lastName, or any other @Column field to null.

When using 2.0.5, this test would pass for us:

``` java
@Test
public void userCanHaveNullColumnWithDefaults() {
    User newUser = new User();
    newUser.setUserId(UUID.randomUUID().toString());
    newUser.setFirstName("John");
    newUser.setAge(42);
    // LastName is null
    userDao.save(newUser);
    // additional asserts
}
```

So this problem with nulls is different than what we saw in 2.0.5. In that version, if the column family had a default validator (for example UTF8Type), then we could persist the entity even if a field of type String was null, but not if it was a non-String.

Now in 2.0.6, the persist seems to fail for any field annotated as @Column that is null, regardless of any default settings on the column family. (The above test fails with 2.0.6)

Pelops does have org.scale7.cassandra.pelops.OperandPolicy#setDeleteIfNull, which will simply remove the column if it's null, which may help.

**Comment by mevivs** [comment]
Hi Jeff ,
This is fixed with 73482037ffe359cfd16d0240c6587f2b5508d243 and 944bfbd877e480350c3e2aebbeb7965e8af58cbf in latest "trunk" branch. 
Could you please take an update, i hope it should resolve the issue.

Thanks,
Vivek

**Comment by everettj** [comment]
This still doesn't work for us using the latest from trunk. We still get a KunderaException if we try to persist an entity with a null column.

The only major difference I see between our code and the test you added is that we configure the EntityManager with Spring, rather than manually building it.

This is our applicationContext.xml:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:aop="http://www.springframework.org/schema/aop"
    xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-3.0.xsd">

    <bean id="entityManagerFactory" class="org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean">
        <property name="persistenceUnitName" value="cassandra_pu" />
    </bean>

</beans>
```

Then in the DAO we configure a container level EntityManager:

``` java
@PersistenceContext(type = PersistenceContextType.EXTENDED)
protected EntityManager em;
```

I'm not sure if that matches what you are configuring manually in your test. I will keep digging on our side to see if I can find any more information.

**Comment by mevivs** [comment]
That looks oK. Not sure. But there is a test case added for the same, here it is:

https://github.com/impetus-opensource/Kundera/blob/trunk/kundera-cassandra/src/test/java/com/impetus/client/persistence/NullableFieldAccessorTest.java

Could you please verify it works and is in align with your scenario?
-Vivek

**Comment by everettj** [comment]
This test does pass for us. And it looks like the right scenario. But this is still broken in our project using the 2.0.7-SNAPSHOT build.

I have uploaded a project that demonstrates this:

https://github.com/everettj/kundera-2-0-6-poc

In that project you should see that UserTest#cannotPersistNullColumn() will pass with an Exception thrown. But the delete method in tearDown() will cause an error. The behavior for us is the same whether we use 2.0.6 or the new 2.0.7-SNAPSHOT build.

Could you give that a try?

**Comment by mevivs** [comment]
Sure.. i will have a look on this.

**Comment by mevivs** [comment]
Hi, i have just commited one change for this and verified with your code branch (by using 2.0.7-SNAPSHOT)

Also i have to remove (expected = KunderaException.class) from "cannotPersistNullColumn()", As now this method can persist NullColumn :)

Please verify.

-Vivek

**Comment by everettj** [comment]
I confirm this is fixed using 2.0.7-SNAPSHOT.

Thanks for your help with this.
